version: "3.8"

services:
  backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_APP=server.py
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - ./Backend:/app
      - backend_data:/app/data

  frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - REACT_APP_API_URL=http://backend:5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - backend
    volumes:
      - ./Frontend:/app
      - /app/node_modules

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx_fixed/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  backend_data:
